/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DiscordClientID": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "DiscordClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordGuildID": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "DiscordToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QuillService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "QuillVPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}