import {is} from "@/model/source/condition/generic/IsCondition"
import {SpellID} from "@/model/source/model/Spell"

export const rangerSpells = is<SpellID>(
  // Level 1 Ranger Spel
  "Alarm",
  "Animal Friendship",
  "Cure Wounds",
  "Detect Magic",
  "Detect Poison and Disease",
  "Ensnaring Strike",
  "Entangle",
  "Fog Cloud",
  "Goodberry",
  "Hail of Thorns",
  "Hunter’s Mark",
  "Jump",
  "Longstrider",
  "Speak with Animals",
  // Level 2 Ranger Spells
  "Aid",
  "Animal Messenger",
  "Barkskin",
  "Beast Sense",
  "Cordon of Arrows",
  "Darkvision",
  "Enhance Ability",
  "Find Traps",
  "Gust of Wind",
  "Lesser Restoration",
  "Locate Animals or Plants",
  "Locate Object",
  "Magic Weapon",
  "Pass without Trace",
  "Protection from Poison",
  "Silence",
  "Spike Growth",
  "Summon Beast",
  // Level 3 Ranger Spells
  "Conjure Animals",
  "Conjure Barrage",
  "Daylight",
  "Dispel Magic",
  "Elemental Weapon",
  "Lightning Arrow",
  "Meld into Stone",
  "Nondetection",
  "Plant Growth",
  "Protection from Energy",
  "Revivify",
  "Speak with Plants",
  "Summon Fey",
  "Water Breathing",
  "Water Walk",
  "Wind Wall",
  // Level 4 Ranger Spells
  "Conjure Woodland Beings",
  "Dominate Beast",
  "Freedom of Movement",
  "Grasping Vine",
  "Locate Creature",
  "Stoneskin",
  "Summon Elemental",
  // Level 5 Ranger Spells
  "Commune with Nature",
  "Conjure Volley",
  "Greater Restoration",
  "Steel Wind Strike",
  "Swift Quiver",
  "Tree Stride",
);
