import {is} from "@/model/source/condition/generic/IsCondition";

export function druidSpell() {
  return is(
    // Cantrips (Level 0 Druid Spells)
    "Druidcraft",
    "Elementalism",
    "Guidance",
    "Mending",
    "Message",
    "Poison Spray",
    "Produce Flame",
    "Resistance",
    "Shillelagh",
    "Spare the Dying",
    "Starry Wisp",
    "Thorn Whip",
    "Thunderclap",
    // Level 1 Druid Spells
    "Animal Friendship",
    "Charm Person",
    "Create or Destroy Water",
    "Cure Wounds",
    "Detect Magic",
    "Detect Poison and Disease",
    "Entangle",
    "Faerie Fire",
    "Fog Cloud",
    "Goodberry",
    "Healing Word",
    "Ice Knife",
    "Jump",
    "Longstrider",
    "Protection from Evil and Good",
    "Purify Food and Drink",
    "Speak with Animals",
    "Thunderwave",
    // Level 2 Druid Spells
    "Aid",
    "Animal Messenger",
    "Augury",
    "Barkskin",
    "Beast Sense",
    "Continual Flame",
    "Darkvision",
    "Enhance Ability",
    "Enlarge/Reduce",
    "Find Traps",
    "Flame Blade",
    "Flaming Sphere",
    "Gust of Wind",
    "Heat Metal",
    "Hold Person",
    "Lesser Restoration",
    "Locate Animals or Plants",
    "Locate Object",
    "Moonbeam",
    "Pass without Trace",
    "Protection from Poison",
    "Spike Growth",
    "Summon Beast",
    // Level 3 Druid Spells
    "Aura of Vitality",
    "Call Lightning",
    "Conjure Animals",
    "Daylight",
    "Dispel Magic",
    "Elemental Weapon",
    "Feign Death",
    "Meld into Stone",
    "Plant Growth",
    "Protection from Energy",
    "Revivify",
    "Sleet Storm",
    "Speak with Plants",
    "Summon Fey",
    "Water Breathing",
    "Water Walk",
    "Wind Wall",
    // Level 4 Druid Spells
    "Blight",
    "Charm Monster",
    "Confusion",
    "Conjure Minor Elementals",
    "Conjure Woodland Beings",
    "Control Water",
    "Divination",
    "Dominate Beast",
    "Fire Shield",
    "Fount of Moonlight",
    "Freedom of Movement",
    "Giant Insect",
    "Grasping Vine",
    "Hallucinatory Terrain",
    "Ice Storm",
    "Locate Creature",
    "Polymorph",
    "Stone Shape",
    "Stoneskin",
    "Summon Elemental",
    "Wall of Fire",
    // Level 5 Druid Spells
    "Antilife Shell",
    "Awaken",
    "Commune with Nature",
    "Cone of Cold",
    "Conjure Elemental",
    "Contagion",
    "Geas",
    "Greater Restoration",
    "Insect Plague",
    "Mass Cure Wounds",
    "Planar Binding",
    "Reincarnate",
    "Scrying",
    "Tree Stride",
    "Wall of Stone",
    // Level 6 Druid Spells
    "Conjure Fey",
    "Find the Path",
    "Flesh to Stone",
    "Heal",
    "Heroes’ Feast",
    "Move Earth",
    "Sunbeam",
    "Transport via Plants",
    "Wall of Thorns",
    "Wind Walk",
    // Level 7 Druid Spells
    "Fire Storm",
    "Mirage Arcane",
    "Plane Shift",
    "Regenerate",
    "Reverse Gravity",
    "Symbol",
    // Level 8 Druid Spells
    "Animal Shapes",
    "Antipathy/Sympathy",
    "Befuddlement",
    "Control Weather",
    "Earthquake",
    "Incendiary Cloud",
    "Sunburst",
    "Tsunami",
    // Level 9 Druid Spells
    "Foresight",
    "Shapechange",
    "Storm of Vengeance",
    "True Resurrection"
  );
}
