import {is} from "@/model/source/condition/generic/IsCondition";
import {SpellID} from "@/model/source/model/Spell";

export const sorcererSpell = is<SpellID>(
  // Cantrips (Level 0 Sorcerer Spells)
  "Acid Splash",
  "Blade Ward",
  "Chill Touch",
  "Dancing Lights",
  "Elementalism",
  "Fire Bolt",
  "Friends",
  "Light",
  "Mage Hand",
  "Mending",
  "Message",
  "Mind Sliver",
  "Minor Illusion",
  "Poison Spray",
  "Prestidigitation",
  "Ray of Frost",
  "Shocking Grasp",
  "Sorcerous Burst",
  "Thunderclap",
  "True Strike",
  // Level 1 Sorcerer Spells
  "Burning Hands",
  "Charm Person",
  "Chromatic Orb",
  "Color Spray",
  "Comprehend Languages",
  "Detect Magic",
  "Disguise Self",
  "Expeditious Retreat",
  "False Life",
  "Feather Fall",
  "Fog Cloud",
  "Grease",
  "Ice Knife",
  "Jump",
  "Mage Armor",
  "Magic Missile",
  "Ray of Sickness",
  "Shield",
  "Silent Image",
  "Sleep",
  "Thunderwave",
  "Witch Bolt",
  // Level 2 Sorcerer Spells
  "Alter Self",
  "Arcane Vigor",
  "Blindness/Deafness",
  "Blur",
  "Cloud of Daggers",
  "Crown of Madness",
  "Darkness",
  "Darkvision",
  "Detect Thoughts",
  "Dragon’s Breath",
  "Enhance Ability",
  "Enlarge/Reduce",
  "Flame Blade",
  "Flaming Sphere",
  "Gust of Wind",
  "Hold Person",
  "Invisibility",
  "Knock",
  "Levitate",
  "Magic Weapon",
  "Mind Spike",
  "Mirror Image",
  "Misty Step",
  "Phantasmal Force",
  "Scorching Ray",
  "See Invisibility",
  "Shatter",
  "Spider Climb",
  "Suggestion",
  "Web",
  // Level 3 Sorcerer Spells
  "Blink",
  "Clairvoyance",
  "Counterspell",
  "Daylight",
  "Dispel Magic",
  "Fear",
  "Fireball",
  "Fly",
  "Gaseous Form",
  "Haste",
  "Hypnotic Pattern",
  "Lightning Bolt",
  "Major Image",
  "Protection from Energy",
  "Sleet Storm",
  "Slow",
  "Stinking Cloud",
  "Tongues",
  "Vampiric Touch",
  "Water Breathing",
  "Water Walk",
  // Level 4 Sorcerer Spells
  "Banishment",
  "Blight",
  "Charm Monster",
  "Confusion",
  "Dimension Door",
  "Dominate Beast",
  "Fire Shield",
  "Greater Invisibility",
  "Ice Storm",
  "Polymorph",
  "Stoneskin",
  "Vitriolic Sphere",
  "Wall of Fire",
  // Level 5 Sorcerer Spells
  "Animate Objects",
  "Bigby’s Hand",
  "Cloudkill",
  "Cone of Cold",
  "Creation",
  "Dominate Person",
  "Hold Monster",
  "Insect Plague",
  "Seeming",
  "Synaptic Static",
  "Telekinesis",
  "Teleportation Circle",
  "Wall of Stone",
  // Level 6 Sorcerer Spells
  "Arcane Gate",
  "Chain Lightning",
  "Circle of Death",
  "Disintegrate",
  "Eyebite",
  "Flesh to Stone",
  "Globe of Invulnerability",
  "Mass Suggestion",
  "Move Earth",
  "Otiluke’s Freezing Sphere",
  "Sunbeam",
  "True Seeing",
  // Level 7 Sorcerer Spells
  "Delayed Blast Fireball",
  "Etherealness",
  "Finger of Death",
  "Fire Storm",
  "Plane Shift",
  "Prismatic Spray",
  "Reverse Gravity",
  "Teleport",
  // Level 8 Sorcerer Spells
  "Demiplane",
  "Dominate Monster",
  "Earthquake",
  "Incendiary Cloud",
  "Power Word Stun",
  "Sunburst",
  // Level 9 Sorcerer Spells
  "Gate",
  "Meteor Swarm",
  "Power Word Kill",
  "Time Stop",
  "Wish",
);