import {is} from "@/model/source/condition/generic/IsCondition";
import {SpellID} from "@/model/source/model/Spell";

export const clericSpell = is<SpellID>(
  // Cantrips (Level 0 Cleric Spells)
  "Guidance",
  "Light",
  "Mending",
  "Resistance",
  "Sacred Flame",
  "Spare the Dying",
  "Thaumaturgy",
  "Toll the Dead",
  "Word of Radiance",
  // Level 1 Cleric Spells
  "Bane",
  "Bless",
  "Command",
  "Create or Destroy Water",
  "Cure Wounds",
  "Detect Evil and Good",
  "Detect Magic",
  "Detect Poison and Disease",
  "Guiding Bolt",
  "Healing Word",
  "Inflict Wounds",
  "Protection from Evil and Good",
  "Purify Food and Drink",
  "Sanctuary",
  "Shield of Faith",
  // Level 2 Cleric Spells
  "Aid",
  "Augury",
  "Blindness/Deafness",
  "Calm Emotions",
  "Continual Flame",
  "Enhance Ability",
  "Find Traps",
  "Gentle Repose",
  "Hold Person",
  "Lesser Restoration",
  "Locate Object",
  "Prayer of Healing",
  "Protection from Poison",
  "Silence",
  "Spiritual Weapon",
  "Warding Bond",
  "Zone of Truth",
  // Level 3 Cleric Spells
  "Animate Dead",
  "Aura of Vitality",
  "Beacon of Hope",
  "Bestow Curse",
  "Clairvoyance",
  "Create Food and Water",
  "Daylight",
  "Dispel Magic",
  "Feign Death",
  "Glyph of Warding",
  "Magic Circle",
  "Mass Healing Word",
  "Meld into Stone",
  "Protection from Energy",
  "Remove Curse",
  "Revivify",
  "Sending",
  "Speak with Dead",
  "Spirit Guardians",
  "Tongues",
  "Water Walk",
  // Level 4 Cleric Spells
  "Aura of Life",
  "Aura of Purity",
  "Banishment",
  "Control Water",
  "Death Ward",
  "Divination",
  "Freedom of Movement",
  "Guardian of Faith",
  "Locate Creature",
  "Stone Shape",
  // Level 5 Cleric Spells
  "Circle of Power",
  "Commune",
  "Contagion",
  "Dispel Evil and Good",
  "Flame Strike",
  "Geas",
  "Greater Restoration",
  "Hallow",
  "Insect Plague",
  "Legend Lore",
  "Mass Cure Wounds",
  "Planar Binding",
  "Raise Dead",
  "Scrying",
  "Summon Celestial",
  // Level 6 Cleric Spells
  "Blade Barrier",
  "Create Undead",
  "Find the Path",
  "Forbiddance",
  "Harm",
  "Heal",
  "Heroes’ Feast",
  "Planar Ally",
  "Sunbeam",
  "True Seeing",
  "Word of Recall",
  // Level 7 Cleric Spells
  "Conjure Celestial",
  "Divine Word",
  "Etherealness",
  "Fire Storm",
  "Plane Shift",
  "Power Word Fortify",
  "Regenerate",
  "Resurrection",
  "Symbol",
  // Level 8 Cleric Spells
  "Antimagic Field",
  "Control Weather",
  "Earthquake",
  "Holy Aura",
  "Sunburst",
  // Level 9 Cleric Spells
  "Astral Projection",
  "Gate",
  "Mass Heal",
  "Power Word Heal",
  "True Resurrection",
);
