import {is} from "@/model/source/condition/generic/IsCondition";

export const warlockSpell = is(
  // Cantrips (Level 0 Warlock Spell)
  "Blade Ward",
  "Chill Touch",
  "Eldritch Blast",
  "Friends",
  "Mage Hand",
  "Mind Sliver",
  "Minor Illusion",
  "Poison Spray",
  "Prestidigitation",
  "Thunderclap",
  "Toll the Dead",
  "True Strike",
  // Level 1 Warlock Spells
  "Armor of Agathys",
  "Arms of Hadar",
  "Bane",
  "Charm Person",
  "Comprehend Languages",
  "Detect Magic",
  "Expeditious Retreat",
  "Hellish Rebuke",
  "Hex",
  "Illusory Script",
  "Protection from Evil and Good",
  "Speak with Animals",
  "Tasha's Hideous Laughter",
  "Unseen Servant",
  "Witch Bolt",
  // Level 2 Warlock Spells
  "Cloud of Daggers",
  "Crown of Madness",
  "Darkness",
  "Enthrall",
  "Hold Person",
  "Invisibility",
  "Mind Spike",
  "Mirror Image",
  "Misty Step",
  "Ray of Enfeeblement",
  "Spider Climb",
  "Suggestion",
  // Level 3 Warlock Spells
  "Counterspell",
  "Dispel Magic",
  "Fear",
  "Fly",
  "Gaseous Form",
  "Hunger of Hadar",
  "Hypnotic Pattern",
  "Magic Circle",
  "Major Image",
  "Remove Curse",
  "Summon Fey",
  "Summon Undead",
  "Tongues",
  "Vampiric Touch",
  // Level 4 Warlock Spells
  "Banishment",
  "Blight",
  "Charm Monster",
  "Dimension Door",
  "Hallucinatory Terrain",
  "Summon Aberration",
  // Level 5 Warlock Spells
  "Contact Other Plane",
  "Dream",
  "Hold Monster",
  "Jallarzi's Storm of Radiance",
  "Mislead",
  "Planar Binding",
  "Scrying",
  "Synaptic Static",
  "Teleportation Circle",
  // Level 6 Warlock Spells
  "Arcane Gate",
  "Circle of Death",
  "Create Undead",
  "Eyebite",
  "Summon Fiend",
  "Tasha's Bubbling Cauldron",
  "True Seeing",
  // Level 7 Warlock Spells
  "Etherealness",
  "Finger of Death",
  "Forcecage",
  "Plane Shift",
  // Level 8 Warlock Spells
  "Befuddlement",
  "Demiplane",
  "Dominate Monster",
  "Glibness",
  "Power Word Stun",
  // Level 9 Warlock Spells
  "Astral Projection",
  "Foresight",
  "Gate",
  "Imprisonment",
  "Power Word Kill",
  "True Polymorph",
  "Weird",
);
